# Generated by Django 4.2.19 on 2025-03-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about_collaboraterequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='CollaborateRequest',
        ),
    ]
